#!/bin/sh
usage(){
  cat << EOF
Description: Perform bootstrap to get standard error for pooled divergence rate. 
Usage: sh $0 -i region.divRate.tsv -n 1000 -o polled.divRate.tsv 
Author: Yumei Li,2017-7-8
Output: ancestor_total_AT ancestor_total_GC totalRate A->T C->T G->C G->T T->C T->G 
Options:
        i     FILE       The input file generated by region_divRate.pl.
        n     INT        The number of sampling for bootsrap.
	o     FILE       The output file name.
        t     FILE       The prefix for tmp file.
        h                print this help message    
EOF
    exit 0
}
[ $1 ] || usage

while getopts "hi:n:o:t:" OPTION
do
    case $OPTION in
        h) usage;;
        i) inFile=$OPTARG;;
        n) number=$OPTARG;;
        o) outFile=$OPTARG;;
        t) tmpFile=$OPTARG;;
        ?) usage;;
    esac
done
declare -i n=1
lines=$(wc -l $inFile|awk '{print $1}')
Rscript /mnt/share/liym/nucleosome/scripts/bootstrap_sampling.R -l=$lines -n=$number -o=${tmpFile}.sample.tsv
awk -v OFS="\t" 'BEGIN{tag=1}{print tag,$0;tag++}' $inFile >${tmpFile}.addNum.tsv

if [ -e $outFile ];then
    rm $outFile
fi

while ((n<=$number))
do
    cut -f $n ${tmpFile}.sample.tsv|perl /mnt/share/liym/bin/join.pl -i1 ${tmpFile}.addNum.tsv -o1 |cut -f2- >$tmpFile
    awk -v OFS="\t" '
        BEGIN{total_AT=0;total_GC=0;AT=0;CT=0;GC=0;GT=0;TC=0;TG=0}
        {total_AT+=$(NF-7);total_GC+=$(NF-6);AT+=$(NF-5);CT+=$(NF-4);GC+=$(NF-3);GT+=$(NF-2);TC+=$(NF-1);TG+=$NF;}
        END{print total_AT,total_GC,(AT+CT+GC+GT+TC+TG)/(total_AT+total_GC),AT/total_AT,CT/total_GC,GC/total_GC,GT/total_GC,TC/total_AT,TG/total_AT;}' $tmpFile >>$outFile
    let n++
done